sonar.organization=juanjodevio
sonar.projectKey=juanjodevio_fluentdlt-lite
sonar.projectName=fluentdlt-lite
sonar.projectVersion=0.1.0

sonar.sourceEncoding=UTF-8
sonar.language=py

sonar.sources=src
sonar.tests=tests

sonar.exclusions=tests/**,tests/integration/alembic/**,tests/.test_dbs/**,**/__pycache__/**
sonar.test.exclusions=tests/integration/alembic/**,tests/.test_dbs/**,**/__pycache__/**

sonar.python.version=3.10,3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml


